### ISSUE TITLE
The Energy loss

### ISSUE THREAD

**Issue by zwy1996** [zbf1991/RRM#14]
Hi,

Nice work! I was sorry to bother you.

I was just getting started in wsss porblem, I was very puzzled about the Energy loss because of the negative value, could you help me about my question. 

Thank you very much.

**Comment by zbf1991** [comment]
If you refer to the Energy loss code, you can find its init =0.0 and there is a minus.  More discussion can be found in the issues of regularized loss of Meng Tang. Moreover, In NeurIps 19, there is another work named gated CRF loss, I have read its code, and there is no negative.

**Comment by zwy1996** [comment]
Thank you very much!
