### ISSUE TITLE
Would you tell me where is the function of evaluation in the RRM_infer.py?

### ISSUE THREAD

**Issue by Zhengyang1995** [zbf1991/RRM#16]
Hey, thank you for your work and your codes. It is actually an impressing research.
I just wonder, when I run the infer file, why there is only output of images, but not the final mIoU value? This is kind strange and different for normal WSSS work.
Thank you for your time and waiting for your reply.

**Comment by zbf1991** [comment]
We do not provide the mIoU code. You can upload your result to the PASCAL VOC website to see the mIoU score. And there are also some mIoU codes that have been publicly available in Github.

**Comment by Zhengyang1995** [comment]
Thank you for your reply.
I just notice you publish your final model and want to test it performance on codes.
I try to test the model by other codes in Github, however, maybe due to the name or other stuff it is hard to utilize them.
It will be nice if you could provide the mIoU code, if not it is also Okay, and thank you again for your work.

**Comment by Zhengyang1995** [comment]
For example, I try to get the infer mIoU from infer_cls.py from PSA, of which and this work are both built in res38. However, it could not work cause of some inconformity. Would you mind providing some advice for available infer codes in Github please?

**Comment by Zhengyang1995** [comment]
Okay, I found the solution.
https://github.com/YudeWang/SEAM
Find the evaluation.py file in SEAM, and choose the evaluation type as "png", set the predict_dir as the output and it will be fine.

Hope these would help others.

And thank again for the author's brilliant work~
