### ISSUE TITLE
permutohedral.hpp:75: Warning 325: Nested struct not currently supported (Neighbors ignored)

### ISSUE THREAD

**Issue by qi0416** [zbf1991/RRM#21]
你好，我在调你的代码的时候输入swig -python -c++ bilateralfilter.i报错了，我看到这个文件原来研究的仓库里的讨论里有说，只是个报错，直接安装就好了，是什么做到的？您是怎么处理的？

**Comment by zbf1991** [comment]
Warning will not influence the next precess.
