### ISSUE TITLE
computer crash

### ISSUE THREAD

**Issue by gentlebreeze1** [zbf1991/RRM#5]
when i run the infer_RRM.py and train_from_cls_weight.py, computer will automatically shut down after a short while. i have 1080ti 11G

**Comment by gentlebreeze1** [comment]
@zbf1991  can you solve my problem?

**Comment by zbf1991** [comment]
1080 TI is okay,  I also run this project on 1080ti and I haven't find the crash. Can you run on another computer?  I have no idea about this problem. Sorry for that.
