### ISSUE TITLE
Did you use COCO pretrain weight when training DeepLabv2-resnet101 ?

### ISSUE THREAD

**Issue by johnnylu305** [zbf1991/RRM#9]
Since you said that your setting of DeepLabv2-resnet101 was the same as the paper, I wonder whether you used COCO pretrain weight or not?

**Comment by zbf1991** [comment]
Yeah. When you refer to the caffe version, the only provided init.model is pretrained on COCO, if you can find the init model without  COCO, please tell me. I really think use this model is not a good choice.

**Comment by johnnylu305** [comment]
Yeah. We are walking on this problem. We will inform you if we find any solution.
